generator/C: fix node test in CI
The node test in mavlink/mavlink CI fails because of:

standard/testsuite.h:29:13: error: ‘mavlink_test_standard’
defined but not used [-Werror=unused-function]

   29 | static void mavlink_test_standard(uint8_t system_id, ...
      |             ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Ignoring the warning fixes CI.