DFReader.py: add hack to avoid struct.error exception
pbarker@bluebottle:/tmp$ mavlogdump.py skyviper-streaming-replay-655.bin
-o /dev/null
Traceback (most recent call last):
  File "/home/pbarker/.local/bin/mavlogdump.py", line 4, in <module>
    __import__('pkg_resources').run_script('pymavlink==2.2.8',
'mavlogdump.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 1503, in run_script
    exec(code, namespace, namespace)
  File
"/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.2.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/mavlogdump.py",
line 136, in <module>
    output.write(m.get_msgbuf())
  File
"/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.2.8-py2.7-linux-x86_64.egg/pymavlink/DFReader.py",
line 178, in get_msgbuf
    struct.pack(self.fmt.msg_struct, *values))
struct.error: argument for 's' must be a string