Add missing string formatting directive and add test
Found with:
pylint --enable too-many-format-args

Fixes:
runtime error
TypeError: not all arguments converted during string formatting

pylint error
E1305: Too many arguments for format string (too-many-format-args)